# Use an official Python base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory into the container
COPY . /app

# Install Python dependencies from requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com -r requirements.txt

# Define the entry point for the container
CMD ["python", "-m", "src.main", "config.json"]